### PR TITLE
Pointing requirements to gvl_5.0.0_alpha branch

### PR DESCRIPTION
**Pull request by almahmoud**

### CODE REVIEW

**Comment by nuwang** [comment]
@almahmoud I'd actually suggest beta here as we are moving into beta?

**Comment by afgane** [comment]
Should we also drop minor minor version? Otherwise, it feels we may end up
with a lot of tiny releases. That distinction can be just kept in the chart
version alone.

**Comment by afgane** [comment]
Required updates:
- [ ] Cloudlaunch-registry
- [ ] Here
- [ ] Requirements of branches
- [ ] Branches in github repos

**Comment by nuwang** [comment]
I guess this is obsolete now.

**Pull request closed without merging**
